# Generated by Django 5.0.1 on 2024-01-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookExperiences', '0002_review_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='userId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='cons',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='experiences',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='pros',
            field=models.TextField(blank=True),
        ),
    ]
